version: 0.2

phases:
  install:
    commands:
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - yum -y update
      - yum -y install google-chrome-stable

  build:
    commands:
      - mvn clean package