version: 0.2

phases:
  install:
    commands:
      - curl https://intoli.com/install-google-chrome.sh | bash
      - mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
      -  google-chrome --version && which google-chrome

  build:
    commands:
      - mvn clean package