version: 0.2

phases:
  install:
    commands:
      - yum install wget
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_arm64.deb
      - dpkg -i google-chrome-stable_current_arm64.deb

  build:
    commands:
      - mvn clean package