version: 0.2

phases:
  install:
    commands:
      - sudo yum install apt-get
      - sudo apt-get install --reinstall systemd
      - google-chrome --version

  build:
    commands:
      - mvn clean package